#version: "3.3"

services:
  postgres:
    image: postgres:latest
    container_name: server_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13ewasz2
      POSTGRES_DB: universidade
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      rede_docker:
        ipv4_address: 172.12.0.15

  app:  
    build: ./projeto/.
    container_name: app_asa
    environment:
      DB_HOST: 172.12.0.15
      DB_USER: postgres
      DB_PASS: 13ewasz2                
    ports:
      - "5000:5000"
    networks:
      rede_docker:
        ipv4_address: 172.12.0.10
    depends_on:
      - postgres

networks:
  rede_docker:
    driver: bridge
    ipam:
      config:
        - subnet: 172.12.0.0/16

volumes:
  pgdata:
    driver: local